### PR TITLE
init

### PR DESCRIPTION
**Pull request by pom11**
check if all `python3 cli/projects.py --help` features work as expected
Screenshot 2022-04-08 at 20 47 52

### CODE REVIEW

**Comment by pom11** [comment]
add 2 more features. 
- [ ] cmd - edit to print results
- [ ] new - add arg to create project

**Comment by pom11** [comment]
@ConanMishler let me know if i have to change something in the `--help` result. 
All features seem stable in dev QA

**Comment by ConanMishler** [comment]
- [ ] 1. Please change these container names:
```
eth-payment
eth-pay-db
```
to these names:
```
payment
payment-db
```
(Remember to update references to `eth-pay-db` in the help text as well.)

- [ ] 2. Please update this line of the help text:
```
--host HOST                                                     Host of eth_pay_db container
```
to say this instead:
```
--host HOST                                                     IP of payment-db container
```

> i dont recommend autofetching ip cause op could have many stacks running on the same machine
I seriously doubt a machine will have more than one EXR ENV stack running. For one thing, the HW resources of running just one stack will make it unlikely. Also, the `app.py` code would have to get a lot fancier than it is now to avoid port conflicts if more than one stack were to be deployed on the same machine. One thing we could do is to auto-fetch the payment-db container IP, then present it as the default value in the help text. That way, if the user doesn't pass the `--host` param, the the default auto-fetched IP will be used, but they can override easily w/ `--host`.

**Comment by ConanMishler** [comment]
- [ ] 3. Add `psycopg2-binary` to `requirements.txt`
- [ ] 4. Add this to `exr_env.sh --update`:
```
pip3 install -r requirements.txt
```

**Comment by ConanMishler** [comment]
- [ ] 5. Now that we've added `psycopg2-binary` to `requirements.txt`, it looks like we also need to remove `psycopg2==2.9.3` from `requirements.txt` bc it's causing errors like the one I DM'd you.
- [ ] 6. Looks like we need to update references to `eth_pay_db` in 6 places in the help text (3 places in regular help, and 3 places in "Arguments Combinations":
```
 --username USERNAME                                             Username for eth_pay_db                                                                       ethproxy 
 --password PASSWORD                                             Password for eth_pay_db                                                                       password 
 --db DB                                                         Database from eth_pay_db                                                                      eth      
```

**Comment by ConanMishler** [comment]
- [ ] 7. This help message:
```
Use this command to get payment_db IP address:
docker inspect $(docker ps | grep payment_db | awk '{print $1}') | sed -nE '/"IPv4Address":[    ]"[[:digit:]]/{s/[      ]*"IPv4Address":[       ]+"([0-9.]+)"//p;}'
```
needs to be corrected to read like this:
```
Use this command to get payment_db IP address:
docker inspect $(docker ps | grep payment_db | awk '{print $1}') | sed -nE '/"IPv4Address":[ \t]"[[:digit:]]/{s/[ \t]*"IPv4Address":[ \t]+"([0-9.]+)"/\1/p;}'
```
Somehow it seems the `\t` got replace with spaces and `\1` was also lost near the end.

**Comment by ConanMishler** [comment]
- [ ] 8. This command shows a lot of truncated fields with `...` after them, and there doesn't seem to be a way to see the full value of those fields:
```
conan@VPS2:~/exrproxy-env/cli$ python3 projects.py --host 172.31.11.45 --balances
Enterprise XRouter Environment Projects CLI

Payment                                                                                                                                                                                                  
 eth_token                                         eth_address                 eth_privkey                                         tie…  tie…  tier1_expe…  tier2_expe…  tier1_expec…  tier2_expec…  pr… 
 d6bf93fc460b2a04ce0c6378873668341694923e86b40a9…  0xcf17e82389612857483C6d5…  0x1a48af2bb766dfdb93db2fbcb17d3513910ed014d687d4b…  0.0…  0.0…  21.875       125.0        -1.0          -1.0          55… 
```

**Comment by ConanMishler** [comment]
- [ ] 9. I created a new project on VPS2, and it is the *only* project that exists on VPS2. It has been assigned `id = 1`. When I try to display line 0 of project table (which doesn't exist), it shows me results for line 1.
```
conan@VPS2:~/exrproxy-env/cli$ python3 projects.py --host 172.31.11.45 --all --id 0
Enterprise XRouter Environment Projects CLI

Project                                                                                                                                                                                                  
 name                                                api_key                                                      api_token_count         used_api_tokens        archive_mode       expires     active   
 55a4e848-c8be-4270-af83-cb3ee00d2698                spoIQTNs02pZHrAauksTqAXGQ7hhAQZ9OKaJUoD72bg                  6000000                 0                      None               None        False   
```
Also, when I try to display line 3 of project table (which also doesn't exist), it shows me this:
```
conan@VPS2:~/exrproxy-env/cli$ python3 projects.py --host 172.31.11.45 --all --id 3
Enterprise XRouter Environment Projects CLI
Traceback (most recent call last):
  File "projects.py", line 212, in <module>
    render_table('project', PROJECT, ID, HOST, DB, USERNAME, PASSWORD)
  File "projects.py", line 92, in render_table
    result = get_table(table, project, id, host, database, user, password)
  File "projects.py", line 85, in get_table
    data = [data.pop(id-1)]
IndexError: pop index out of range
```
Not quite "bozo proof" but maybe that's ok for this particular tool, since no *bozos* should be using this tool anyway. 🙏

**Comment by ConanMishler** [comment]
- [ ] 10. The `--active` param seems to work fine to *invert* the current `active` status, but the `--archive` param doesn't invert the current `archive_mode` status:
```
conan@VPS2:~/exrproxy-env/cli$ python3 projects.py --host 172.31.11.45 --project 55a4e848-c8be-4270-af83-cb3ee00d2698 --active
Enterprise XRouter Environment Projects CLI

Project                                                                                                                                                                                                  
                                                                                                                                                                                                         
 name                                                    55a4e848-c8be-4270-af83-cb3ee00d2698                                                                                                            
 api_key                                                 spoIQTNs02pZHrAauksTqAXGQ7hhAQZ9OKaJUoD72bg                                                                                                     
 api_token_count                                         6000000                                                                                                                                         
 used_api_tokens                                         0                                                                                                                                               
 archive_mode                                            None                                                                                                                                            
 expires                                                 None                                                                                                                                            
 active                                                  True
```
Worked perfectly, but then...
```
conan@VPS2:~/exrproxy-env/cli$ python3 projects.py --host 172.31.11.45 --project 55a4e848-c8be-4270-af83-cb3ee00d2698 --archive
Enterprise XRouter Environment Projects CLI

Project                                                                                                                                                                                                  
                                                                                                                                                                                                         
 name                                                    55a4e848-c8be-4270-af83-cb3ee00d2698                                                                                                            
 api_key                                                 spoIQTNs02pZHrAauksTqAXGQ7hhAQZ9OKaJUoD72bg                                                                                                     
 api_token_count                                         6000000                                                                                                                                         
 used_api_tokens                                         0                                                                                                                                               
 archive_mode                                            None                                                                                                                                            
 expires                                                 None                                                                                                                                            
 active                                                  True                                                        
```
Did not invert `archive_mode` to `True`, maybe because it wasn't a boolean `False` to begin with?

**Comment by ConanMishler** [comment]
- [ ] 11. These help statements are clear:
```
 --archive        Change the archive boolean of a project in a Project table                                 
 --active         Change the active boolean of a project in a Project table     
```
But these help statements could easily be misinterpreted to mean, "set the bool value to `False`":
```
--project f8cc8cfc-e34a-4c66-86ae-2fef9d29da64 --archive        Change f8cc8cfc-e34a-4c66-86ae-2fef9d29da64 archive mode boolean to NOT ARCHIVE MODE BOOLEAN           
 --project f8cc8cfc-e34a-4c66-86ae-2fef9d29da64 --active         Change f8cc8cfc-e34a-4c66-86ae-2fef9d29da64 active boolean to NOT ACTIVE BOOLEAN 
```
I'd suggest changing those last to help messages to:
```
--project f8cc8cfc-e34a-4c66-86ae-2fef9d29da64 --archive        Toggle f8cc8cfc-e34a-4c66-86ae-2fef9d29da64 archive mode boolean
 --project f8cc8cfc-e34a-4c66-86ae-2fef9d29da64 --active         Toggle f8cc8cfc-e34a-4c66-86ae-2fef9d29da64 active boolean
```

**Comment by ConanMishler** [comment]
- [ ] 12. This one didn't seem to set the date properly:
```
conan@VPS2:~/exrproxy-env/cli$ python3 projects.py --host 172.31.11.45 --project 55a4e848-c8be-4270-af83-cb3ee00d2698 --date 2022/4/18
Enterprise XRouter Environment Projects CLI

Project                                                                                                                                                                                                  
                                                                                                                                                                                                         
 name                                                    55a4e848-c8be-4270-af83-cb3ee00d2698                                                                                                            
 api_key                                                 spoIQTNs02pZHrAauksTqAXGQ7hhAQZ9OKaJUoD72bg                                                                                                     
 api_token_count                                         6000000                                                                                                                                         
 used_api_tokens                                         0                                                                                                                                               
 archive_mode                                            None                                                                                                                                            
 expires                                                 None                                                                                                                                            
 active                                                  True                                                                                                                                            

```

**Review by ConanMishler — APPROVED** [review]
Another beautiful work of art by 🦈

**Pull request merged**
