### PR TITLE
add optional parameter 'chainstate_mount_dir'.

### PR DESCRIPTION
**Pull request by tryiou**
add optional parameter 'chainstate_mount_dir' to use in alldaemons.yaml during setup.
tested on my side, working as intended:
custom.yaml:
>    - name: BTC
>      image: blocknetdx/bitcoin:v0.20.0
>      config_mount_dir: /data/snode
>      data_mount_dir: /data/snode
>      chainstate_mount_dir: /snode

produce dockercompose.yml:

>    volumes:
>      - /data/snode/BTC/config:/opt/blockchain/config
>      - /data/snode/BTC/data:/opt/blockchain/data
>      - /snode/BTC/data/chainstate:/opt/blockchain/data/chainstate

if this variable is not set in custom.yaml, script ignore this mountpoint:
>    - name: SNODE # DO NOT DELETE
>      image: blocknetdx/servicenode:latest # DO NOT DELETE
>      config_mount_dir: /snode # DO NOT DELETE
>      data_mount_dir: /snode # DO NOT DELETE

produce:
>    volumes:
>      - /snode/snode/config:/opt/blockchain/config
>      - /snode/snode/data:/opt/blockchain/data

### CODE REVIEW

**Review by ConanMishler — CHANGES_REQUESTED** [review]
Hmm... When I test this on the current `alldaemons.yaml` I get errors and `dockercompose-custom.yaml` is not generated correctly. Please hold off on merging this till I figure out if I'm doing something wrong or if it's a bug in the j2 template.

I'm seeing these errors:
```
12/08/2021 09:59:10 AM INFO - invalid config in YAML for BTC:
missing ['legacy', 'chainstate_mount_dir', 'deprecatedrpc']
12/08/2021 09:59:10 AM INFO - invalid config in YAML for LTC:
missing ['legacy', 'chainstate_mount_dir', 'deprecatedrpc']
12/08/2021 09:59:10 AM INFO - invalid config in YAML for DGB:
missing ['legacy', 'chainstate_mount_dir', 'deprecatedrpc']
```
And then the `dockercompose-custom.yaml` that's generated contains only 2 entries - one for snode and one for xquery. (It should contain entries for all entries in `alldaemons.yaml`.)

**Comment by tryiou** [comment]
You are right i didn't test my change with enough care, the snode is a special case and won't use it.
Right now this code produce error as soon as 'chainstate_mount_dir' is not defined, which is not ideal.
Searching for more and correcting this asap.

**Comment by tryiou** [comment]
Ok, last commit remove `chainstate_mount_dir` from the list of `required` items,
Seems working fine now,
tried to build a custom.yaml without any `chainstate_mount_dir`, worked,
tried another with few `chainstate_mount_dir` and some other without, worked.

**Review by ConanMishler — APPROVED** [review]
Ok, tested the latest changes. Works beautifully! :-)

**Pull request merged**
