### PR TITLE
check in template_vars(template_path) func

### PR DESCRIPTION
**Pull request by tryiou**
check 'chainstate_mount_dir' exist in list before trying to remove it.

### CODE REVIEW

**Review by walkjivefly — COMMENTED** [review]
This is the voodoo for splitting chain stuff across potentially mixed disk types, right?

It looks OK to me but I'm not sure how it fits in with @pom11 and @ConanMishler pending changes to alldaemons.yaml and the workflow.

**Comment by ConanMishler** [comment]
> This is the voodoo for splitting chain stuff across potentially mixed disk types, right?
> 
> It looks OK to me but I'm not sure how it fits in with @pom11 and @ConanMishler pending changes to alldaemons.yaml and the workflow.

Yes, it is that very voodoo.

**Review by ConanMishler — APPROVED** [review]
This is a very small enhancement. I've tested it and it doesn't break anything. I doubt it will conflict with the changes coming in PR #79 from @pom11. If it does, I'm sure he can easily resolve the conflicts.

**Comment by pom11** [comment]
which entry uses `chainstate_`?

**Comment by ConanMishler** [comment]
> which entry uses `chainstate_`?

@pom11  `chainstate_mount_dir` is an optional mount dir which can be added to any coin entry in the `.yaml`. @tryiou wanted to be able to mount the chainstate data on a fast SSD drive, while mounting less speed-dependent data onto cheaper HDD drives (or something like that).

**Review by pom11 — COMMENTED** [review]
if no entry in `.yaml` input file uses `chainstate_` L29-30 should be removed

**Comment by pom11** [comment]
> > which entry uses `chainstate_`?
> 
> @pom11 `chainstate_mount_dir` is an optional mount dir which can be added to any coin entry in the `.yaml`. @tryiou wanted to be able to mount the chainstate data on a fast SSD drive, while mounting less speed-dependent data onto cheaper HDD drives (or something like that).

is this entry in jinja2 templates files?

**Comment by ConanMishler** [comment]
> > > which entry uses `chainstate_`?
> > 
> > 
> > @pom11 `chainstate_mount_dir` is an optional mount dir which can be added to any coin entry in the `.yaml`. @tryiou wanted to be able to mount the chainstate data on a fast SSD drive, while mounting less speed-dependent data onto cheaper HDD drives (or something like that).
> 
> is this entry in jinja2 templates files?

Yes, from a previous PR that @tryiou made.

**Comment by pom11** [comment]
ok

**Pull request merged**
