### PR TITLE
updated link to download env_installer.sh

### PR DESCRIPTION
**Pull request by ConanMishler**

### CODE REVIEW

**Review by walkjivefly — COMMENTED** [review]
We should mention it's necessary to run the script twice, following the instructions to run it a second time after it logs you out. Wouldn't be a bad idea to explain that the reason it is required to be run (again) after 1 October is to accommodate a Python dependency broken by a 3rd party.

Also that the script only configures the Python environment for the exrproxy-env located in the user's home directory. If they have it located elsewhere they will need to switch to using it in the home directory or engage in some manual tweaking.

**Comment by ConanMishler** [comment]
> We should mention it's necessary to run the script twice, following the instructions to run it a second time after it logs you out. Wouldn't be a bad idea to explain that the reason it is required to be run (again) after 1 October is to accommodate a Python dependency broken by a 3rd party.
> 
> Also that the script only configures the Python environment for the exrproxy-env located in the user's home directory. If they have it located elsewhere they will need to switch to using it in the home directory or engage in some manual tweaking.

Good points! Will do!

**Comment by ConanMishler** [comment]
> We should mention it's necessary to run the script twice, following the instructions to run it a second time after it logs you out. Wouldn't be a bad idea to explain that the reason it is required to be run (again) after 1 October is to accommodate a Python dependency broken by a 3rd party.
> 
> Also that the script only configures the Python environment for the exrproxy-env located in the user's home directory. If they have it located elsewhere they will need to switch to using it in the home directory or engage in some manual tweaking.

@walkjivefly I've updated the README as per your suggestions. Please have a look and either approve the PR or let me know what else should change. Thx!

**Review by walkjivefly — APPROVED** [review]
LGTM

**Comment by ConanMishler** [comment]
> You could change "detect" to "detects" in line 21 but LGTM

@walkjivefly  Ha! I thought I could make this small change and then merge without bothering you again, but now it wants your approval again! 😜

**Review by walkjivefly — APPROVED** [review]

**Pull request merged**
